[phishtank]
username = ''
password = ''
url = '''
last_seen = ''

[openphish]
url = ''

[collector]
kit_directory = 'kits'
max_links_per_directory = 100

[server]
host = '0.0.0.0'
port = 8888

[elasticsearch]
host = 'localhost'
port = '9200'
user = ''
pass = ''
